apiVersion: v1
kind: ReplicationController
metadata:
  name: tensorflow-ps-rc-gpu
  namespace: dwj
spec:
  replicas: 1
  selector:
    name: tensorflow-ps-gpu
  template:
    metadata:
      labels:
        name: tensorflow-ps-gpu
        role: ps-gpu
    spec:
      containers:
        - name: ps-gpu
          image: tensorflow/tensorflow:1.13.1-gpu-py3-jupyter
          ports:
           - containerPort: 2222
#          resources:
#            limits:
#              nvidia.com/gpu: 1
          volumeMounts:
            - name: nfs-storage
              mountPath: /tf/shared
      volumes:
        - name: nfs-storage
          nfs:
            server: 10.244.1.0
            path: "/home/dwj_temp/shared"

