apiVersion: v1
kind: ReplicationController
metadata:
  name: tensorflow-ps-rc
  namespace: dwj
spec:
  replicas: 2
  selector:
    name: tensorflow-ps
  template:
    metadata:
      labels:
        name: tensorflow-ps
        role: ps
    spec:
      containers:
        - name: ps
          image: tensorflow/tensorflow:1.13.1-py3-jupyter
          ports:
            - containerPort: 2222
          volumeMounts:
            - name: nfs-storage
              mountPath: /shared
      volumes:
        - name: nfs-storage      
          nfs:
            server: 10.244.1.1
            path: "/data/shared"
