apiVersion: v1
kind: ReplicationController
metadata:
  name: tensorflow-wk-rc
  namespace: dwj
spec:
  replicas: 2
  selector:
    name: tensorflow-worker
  template:
    metadata:
      labels:
        name: tensorflow-worker
        role: worker
    spec:
      containers:
        - name: worker
          image: tensorflow/tensorflow:1.13.1-py3-jupyter
          ports:
            - containerPort: 2222
          volumeMounts:
            - name: nfs-storage
              mountPath: /shared
      volumes:
        - name: nfs-storage
          nfs:
            server: 10.244.1.1
            path: "/data/shared"
