apiVersion: v1
kind: ReplicationController
metadata:
  name: ps-rc-gpu
  namespace: dwj
spec:
  replicas: 1
  selector:
    name: tensorflow-ps-gpu
  template:
    metadata:
      labels:
        name: tensorflow-ps-gpu
        role: ps-gpu
    spec:
      containers:
        - name: ps-gpu
          image: tensorflow/tensorflow:1.13.1-gpu-py3-jupyter
          ports:
           - containerPort: 2222
          volumeMounts:
            - name: nfs-storage
              mountPath: /tf/shared
      nodeSelector:
        disktype: dwj1
      volumes:
        - name: nfs-storage
          nfs:
            server: 10.244.1.1
            path: "/home/dwj_temp/shared/distribute-gpu/distribute"

