apiVersion: v1
kind: Service
metadata:
  labels:
    name: tensorflow-worker-gpu
    role: service
  name: tensorflow-worker-gpu-service
  namespace: dwj
spec:
  ports:
    - port: 6006
      targetPort: 6006
      protocol: TCP
  type: NodePort
  selector:
    name: tensorflow-worker-gpu
